/* ============================================================================
   DANE PROMOCJI — THERMOSILESIA / PANEL DLA INSTALATORÓW
   ============================================================================
   TEN PLIK AKTUALIZUJEMY CO MIESIĄC na podstawie nowej ulotki PDF.
   Instrukcja aktualizacji: patrz plik "INSTRUKCJA_AKTUALIZACJI.md"
   w katalogu głównym strony.

   Źródło danych (bieżąca edycja): ulotka "Thermosilesia - Ulotka
   promocyjna - sierpień 2026 v3" (nr P/TS/P/PL/2026.08.17).
   ============================================================================ */

const MONTH_LABEL = 'Sierpień 2026';
const LEAFLET_REF = 'P/TS/P/PL/2026.08.17';

/* Lokalizacja, dla której panel pokazuje 7-dniową prognozę pogody w
   nagłówku (istotne przy planowaniu montaży klimatyzacji/pomp ciepła).
   Domyślnie: Katowice — centralny punkt woj. śląskiego, obszaru działania
   Thermosilesia. Przy wdrożeniu panelu gdzie indziej wystarczy podmienić
   lat/lon poniżej. */
const WEATHER_LOCATION = { name: 'woj. śląskie', lat: 50.2649, lon: 19.0238 };

/* Wspólne, powtarzalne bloki tekstu prawnego z ulotki */
const TERMS = {
  standard:
    'Promocja nie łączy się z innymi promocjami oraz ofertą produktów wyprzedażowych. Oferta skierowana jest tylko i wyłącznie do firm z branży HVAC. Przedstawiona oferta cenowa ma charakter informacyjny, nie stanowi oferty handlowej w rozumieniu Art. 66 par. 1 Kodeksu Cywilnego.',
  hvacOnly:
    'Oferta urządzeń jest skierowana wyłącznie do firm z branży HVAC. Brak zgłoszenia do EKG. Brak refundacji za uruchomienie. Pompę uruchamia wykonawca instalacji.',
  setOnly: 'Sprzedaż pomp wyłącznie w kompletach (jednostka wewnętrzna + jednostka zewnętrzna).',
};

/* ============================================================================
   MARKA: ROTENSO
   ============================================================================ */

const ROTENSO_CATEGORIES = [
  // ---------------------------------------------------------------- KLIMATYZACJE
  {
    id: 'revio',
    group: 'klimatyzacje',
    groupLabel: 'Klimatyzacje',
    name: 'Revio 4+1',
    kicker: 'Promocja 4+1',
    tagline: 'Kup 4 jednostki Revio, piątą odbierz za symboliczną złotówkę',
    description:
      'Najtańsza jednostka z zamówienia trafia do Ciebie za 1 zł netto. Modele można dowolnie mieszać w ramach jednego zamówienia — pełna elastyczność doboru mocy dla każdej instalacji.',
    icon: 'splitAC',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/3b8768ca-8f17-4d8d-b3ce-4b9fa9136070.jpg',
    gradient: ['#d9711b', '#7a2e0a'],
    glow: '#ff9d4d',
    badges: [
      { icon: 'shuffle', text: 'Miksuj dowolnie' },
      { icon: 'tag', text: '4+1' },
    ],
    priceLabel: 'Najtańszy zestaw z zamówienia za',
    priceValue: '1',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: '01.08.2026 – 31.08.2026 lub do wyczerpania stanów magazynowych',
    detail: {
      type: 'simple-list',
      note: 'Dostępne modele w promocji: RO26Xi/Xo, RO35Xi/Xo, RO50Xi/Xo.',
      items: ['RO26Xi / RO26Xo', 'RO35Xi / RO35Xo', 'RO50Xi / RO50Xo'],
      footnote: 'Zamówienia prosimy składać u opiekunów handlowych.',
    },
  },

  // ---------------------------------------------------------------- POMPY CIEPŁA
  {
    id: 'windmi',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Windmi Monoblock',
    kicker: 'Pompa Ciepła',
    tagline: 'Kompaktowa pompa ciepła monoblok powietrze-woda w agresywnych cenach.',
    description:
      'Jedna zwarta jednostka zewnętrzna — bez konieczności prowadzenia instalacji czynnika chłodniczego do budynku. Prosty montaż, 2 lata gwarancji.',
    icon: 'monoblock',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/05d00350-c3ac-4d90-8386-75a5749ddf93.jpg',
    gradient: ['#55622f', '#202812'],
    glow: '#a7cf4f',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '3999',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Windmi 6 kW', 'WIM60X1 R14 2GW', '6 099 zł'],
        ['Rotenso Windmi 8 kW', 'WIM80X1 R14 2GW', '3 999 zł'],
        ['Rotenso Windmi 10 kW', 'WIM100X1 R14 2GW', '4 199 zł'],
        ['Rotenso Windmi 12 kW', 'WIM120X3 R14 2GW', '6 999 zł'],
        ['Rotenso Windmi 14 kW', 'WIM140X3 R14 2GW', '7 299 zł'],
      ],
      footnote: TERMS.hvacOnly,
    },
  },
  {
    id: 'heatmi',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Heatmi Split',
    kicker: 'Pompa Ciepła',
    tagline: 'Split powietrze-woda w atrakcyjnym pakiecie cenowym.',
    description:
      'Zestaw jednostki wewnętrznej i zewnętrznej sprzedawany wyłącznie w komplecie. 2 lata gwarancji.',
    icon: 'hydroSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/44def040-c36b-4419-80ec-e83cb137a51c.jpg',
    gradient: ['#8a5227', '#341e0d'],
    glow: '#e0a05c',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5199',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Heatmi 4 kW', 'HES60X1I R14 2GW + HES40X1o R14 2GW', '5 599 zł'],
        ['Rotenso Heatmi 8 kW', 'HES80X13I R14 2GW + HES80X1o R14 2GW', '5 199 zł'],
        ['Rotenso Heatmi 10 kW', 'HES100X13I R14 2GW + HES100X1o R14 2GW', '5 399 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'aquami-mono',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Aquami Monoblock',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Wydajny monoblok powietrze-woda do większych instalacji.',
    description: 'Zwarta konstrukcja, wysoka moc grzewcza, 2 lata gwarancji.',
    icon: 'monoblock',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/0727d3bb-1add-49e3-9e46-76fffb865f74.jpg',
    gradient: ['#1f6b45', '#0a2c1c'],
    glow: '#4fd18a',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '8500',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Aquami Monoblock 8 kW', 'AQM80X1 R14 2GW', '8 500 zł'],
        ['Rotenso Aquami Monoblock 10 kW', 'AQM100X1R 14 2GW', '8 700 zł'],
        ['Rotenso Aquami Monoblock 12 kW', 'AQM120X3 R14 2GW', '11 200 zł'],
      ],
      footnote: TERMS.hvacOnly,
    },
  },
  {
    id: 'aquami-split',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Aquami Split',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Split powietrze-woda — pełna linia mocy od 8 do 16 kW.',
    description: 'Zestaw jednostki wewnętrznej i zewnętrznej sprzedawany wyłącznie w komplecie. 2 lata gwarancji.',
    icon: 'hydroSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/f9b7e36a-f55e-408b-b01d-de93396e8342.jpg',
    gradient: ['#0f4a4a', '#031c1c'],
    glow: '#34d6c6',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '6299',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Aquami Split 8 kW', 'AQS100X13I R14 2GW + AQS80X1o R14 2GW', '6 299 zł'],
        ['Rotenso Aquami Split 10 kW', 'AQS100X13I R14 2GW + AQS100X1o R14 2GW', '6 699 zł'],
        ['Rotenso Aquami Split 12 kW', 'AQS160X13I R14 2GW + AQS120X3o R14 2GW', '8 799 zł'],
        ['Rotenso Aquami Split 14 kW', 'AQS160X13I R14 2GW + AQS140X3o R14 2GW', '8 799 zł'],
        ['Rotenso Aquami Split 16 kW', 'AQS160X13I R14 2GW + AQS160X3o R14 2GW', '9 299 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'aquami-aio',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Aquami All In One',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Wszystko w jednej obudowie — zasobnik CWU zintegrowany z modułem hydraulicznym.',
    description: 'Kompaktowe rozwiązanie do kotłowni o ograniczonej powierzchni. 2 lata gwarancji.',
    icon: 'aio',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/dd949153-5c28-4d3e-86bc-55822f134efb.jpg',
    gradient: ['#6e2438', '#2a0e17'],
    glow: '#e0577a',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '15899,50',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Aquami AIO 12 kW', 'AQS160T240X13i R14 2GW + AQS120X3o R14 2GW', '15 899,50 zł'],
        ['Rotenso Aquami AIO 14 kW', 'AQS160T240X13i R14 2GW + AQS140X3o R14 2GW', '15 899,50 zł'],
        ['Rotenso Aquami AIO 16 kW', 'AQS160T240X13i R14 2GW + AQS160X3o R14 2GW', '16 399,50 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'airmi-mono-white',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Monoblock White',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Monoblok powietrze-woda w wersji kolorystycznej White.',
    description: '2 lata gwarancji, pełna linia mocy od 8 do 16 kW.',
    icon: 'monoblock',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/b40a6cd2-dba4-4465-bdc5-162b6797e6cf.jpg',
    gradient: ['#1f5f73', '#0a2833'],
    glow: '#5ad2f0',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '4999',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Monoblock 8 kW', 'AIMW80X1 R14 2GW', '4 999 zł'],
        ['Rotenso Airmi Monoblock 10 kW', 'AIMW100X1 R14 2GW', '5 199 zł'],
        ['Rotenso Airmi Monoblock 12 kW', 'AIMW120X3 R14 2GW', '6 699 zł'],
        ['Rotenso Airmi Monoblock 14 kW', 'AIMW140X3 R14 2GW', '7 299 zł'],
        ['Rotenso Airmi Monoblock 16 kW', 'AIMW160X3 R14 2GW', '7 599 zł'],
      ],
      footnote: TERMS.hvacOnly,
    },
  },
  {
    id: 'airmi-mono-graphite',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Monoblock Graphite',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Monoblok powietrze-woda w eleganckiej wersji Graphite.',
    description: '2 lata gwarancji, pełna linia mocy od 8 do 16 kW.',
    icon: 'monoblock',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/371c805e-c0e5-434c-8861-b66bcd63d32f.jpg',
    gradient: ['#9a6a1e', '#3d2a0c'],
    glow: '#ffcf6b',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5499',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Monoblock 8 kW', 'AIMB80X1 R14 2GW', '5 499 zł'],
        ['Rotenso Airmi Monoblock 10 kW', 'AIMB100X1 R14 2GW', '5 699 zł'],
        ['Rotenso Airmi Monoblock 12 kW', 'AIMB120X3 R14 2GW', '7 199 zł'],
        ['Rotenso Airmi Monoblock 14 kW', 'AIMB140X3 R14 2GW', '7 799 zł'],
        ['Rotenso Airmi Monoblock 16 kW', 'AIMB160X3 R14 2GW', '8 099 zł'],
      ],
      footnote: TERMS.hvacOnly,
    },
  },
  {
    id: 'airmi-mono-grey',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Monoblock Grey',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Monoblok powietrze-woda w wersji kolorystycznej Grey.',
    description: '2 lata gwarancji, pełna linia mocy od 8 do 16 kW.',
    icon: 'monoblock',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/1c56ed5a-03a9-44e5-b2ed-dce75afdfcc4.jpg',
    gradient: ['#6f5138', '#2a1e13'],
    glow: '#d9a066',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5499',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Monoblock 8 kW', 'AIMG80X1 R14 2GW', '5 499 zł'],
        ['Rotenso Airmi Monoblock 10 kW', 'AIMG100X1 R14 2GW', '5 699 zł'],
        ['Rotenso Airmi Monoblock 12 kW', 'AIMG120X3 R14 2GW', '7 199 zł'],
        ['Rotenso Airmi Monoblock 14 kW', 'AIMG140X3 R14 2GW', '7 799 zł'],
        ['Rotenso Airmi Monoblock 16 kW', 'AIMG160X3 R14 2GW', '8 099 zł'],
      ],
      footnote: TERMS.hvacOnly,
    },
  },
  {
    id: 'airmi-split-white',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Split White',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Split powietrze-woda w wersji kolorystycznej White.',
    description: 'Sprzedaż wyłącznie w kompletach, 2 lata gwarancji.',
    icon: 'hydroSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/e8ee2f0a-e892-44e3-b537-b7155d54ceb6.jpg',
    gradient: ['#4a3468', '#1c1430'],
    glow: '#b58cf0',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5499',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Split 8 kW', 'AIS80X13I R14 2GW + AISW80X1o R14 2GW', '5 499 zł'],
        ['Rotenso Airmi Split 10 kW', 'AIS100X13I R14 2GW + AISW100X1o R14 2GW', '5 799 zł'],
        ['Rotenso Airmi Split 12 kW', 'AIS120X13I R14 2GW + AISW120X3o R14 2GW', '7 299 zł'],
        ['Rotenso Airmi Split 14 kW', 'AIS140X13I R14 2GW + AISW140X3o R14 2GW', '7 999 zł'],
        ['Rotenso Airmi Split 16 kW', 'AIS160X13I R14 2GW + AISW160X3o R14 2GW', '7 999 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'airmi-split-grey',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Split Grey',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Split powietrze-woda w wersji kolorystycznej Grey.',
    description: 'Sprzedaż wyłącznie w kompletach, 2 lata gwarancji.',
    icon: 'hydroSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/27cdc9e1-e3fa-4f91-a1cb-e269fdabb68f.jpg',
    gradient: ['#a5811b', '#4a3a0a'],
    glow: '#ffdc73',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5999',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Split 8 kW', 'AIS80X13I R14 2GW + AISG80X1o R14 2GW', '5 999 zł'],
        ['Rotenso Airmi Split 10 kW', 'AIS100X13I R14 2GW + AISG100X1o R14 2GW', '6 299 zł'],
        ['Rotenso Airmi Split 12 kW', 'AIS120X13I R14 2GW + AISG120X3o R14 2GW', '7 799 zł'],
        ['Rotenso Airmi Split 14 kW', 'AIS140X13I R14 2GW + AISG140X3o R14 2GW', '8 499 zł'],
        ['Rotenso Airmi Split 16 kW', 'AIS160X13I R14 2GW + AISG160X3o R14 2GW', '8 499 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'airmi-split-graphite',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Airmi Split Graphite',
    kicker: 'Mega ceny! Łap okazję!',
    tagline: 'Split powietrze-woda w eleganckiej wersji Graphite.',
    description: 'Sprzedaż wyłącznie w kompletach, 2 lata gwarancji.',
    icon: 'hydroSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/5f8c043e-d126-4f01-8321-e2d64774553e.jpg',
    gradient: ['#566b28', '#212a0f'],
    glow: '#b9d95c',
    badges: [{ icon: 'shield', text: '2 lata gwarancji' }],
    priceLabel: 'Ceny już od',
    priceValue: '5999',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Lipiec – Wrzesień 2026, oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'pricetable',
      columns: ['Model', 'Symbol', 'Cena netto'],
      rows: [
        ['Rotenso Airmi Split 8 kW', 'AIS80X13I R14 2GW + AISB80X1o R14 2GW', '5 999 zł'],
        ['Rotenso Airmi Split 10 kW', 'AIS100X13I R14 2GW + AISB100X1o R14 2GW', '6 299 zł'],
        ['Rotenso Airmi Split 12 kW', 'AIS120X13I R14 2GW + AISB120X3o R14 2GW', '7 799 zł'],
        ['Rotenso Airmi Split 14 kW', 'AIS140X13I R14 2GW + AISB140X3o R14 2GW', '8 499 zł'],
        ['Rotenso Airmi Split 16 kW', 'AIS160X13I R14 2GW + AISB160X3o R14 2GW', '8 499 zł'],
      ],
      footnote: TERMS.hvacOnly + ' ' + TERMS.setOnly,
    },
  },
  {
    id: 'aquami-multi',
    group: 'pompy',
    groupLabel: 'Pompy ciepła',
    name: 'Aquami Multi Split',
    kicker: 'Gratis transport',
    tagline: 'Tryb powietrze-powietrze LUB powietrze-woda — jedna jednostka zewnętrzna, wiele możliwości.',
    description:
      'Uniwersalna pompa ciepła multi split łącząca klimatyzację pomieszczeń i ogrzewanie wody/instalacji grzewczej z jednej jednostki zewnętrznej.',
    icon: 'multiSplit',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/6ed3e09b-4eee-4bc9-a6f8-6c4629a281ca.jpg',
    gradient: ['#0f2b45', '#03101c'],
    glow: '#4d8fdb',
    badges: [
      { icon: 'truck', text: 'Gratis transport' },
      { icon: 'shield', text: '2 lata gwarancji' },
      { icon: 'dualMode', text: 'Powietrze-powietrze / powietrze-woda' },
    ],
    priceLabel: 'Cena zestawu',
    priceValue: '7900',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: '01.07.2026 – 30.09.2026 lub do wyczerpania stanów magazynowych',
    detail: {
      type: 'simple-list',
      note: 'Rotenso Aquami Multi Split — AQMS80X1I 2GW + H100XM4 R16',
      items: ['Jednostka zewnętrzna: AQMS80X1I 2GW', 'Moduł hydrauliczny: H100XM4 R16'],
      footnote: 'Regulamin promocji dostępny na www.thermosilesia.pl.',
    },
  },

  // ---------------------------------------------------------------- PAKIETY PREMIUM
  {
    id: 'pakiet-aquami-8-10',
    group: 'pakiety',
    groupLabel: 'Pakiety Premium',
    name: 'Pakiet Premium Aquami Split 8/10 kW',
    kicker: 'Pakiet Premium z akcesoriami',
    tagline: 'Kompletny zestaw pompy ciepła z osprzętem hydraulicznym w jednej, niższej cenie.',
    description: 'W pakiecie: zbiornik buforowy, wspornik montażowy Ivensis, zasobnik CWU, pompa obiegowa, separator zanieczyszczeń i zawór strefowy.',
    icon: 'bundle',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/e629f766-2895-4029-8c62-74c7e7c9a00d.png',
    gradient: ['#7a5a17', '#2a1e07'],
    glow: '#ffd479',
    badges: [{ icon: 'shield', text: '5 lat gwarancji na pompę ciepła' }],
    priceLabel: 'Pakiet 8 kW już od',
    priceValue: '13000',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'bundle',
      variants: [
        { label: 'Aquami Split 8 kW', oldPrice: '14 373,25 zł', newPrice: '13 000 zł', savings: '1 373,25 zł' },
        { label: 'Aquami Split 10 kW', oldPrice: '15 023,25 zł', newPrice: '13 400 zł', savings: '1 623,25 zł' },
      ],
      mainItem: { name: 'Pompa ciepła Rotenso Aquami Split 8 kW lub 10 kW', code: 'AQS80X1o + AQS100X13i lub AQS100X1o + AQS100X13i', brand: 'rotenso' },
      accessories: [
        { name: 'Zbiornik buforowy Thermos Store 50 l', code: 'AQT50SBHA', brand: 'thermos' },
        { name: 'Wspornik montażowy do pomp ciepła Ivensis', code: 'IHG520S', brand: 'ivensis' },
        { name: 'Zbiornik CWU ze stali emaliowanej Thermos Ceramic 200 l', code: 'AQT200EC1A', brand: 'thermos' },
        { name: 'Pompa obiegowa', code: 'RASHSP-PH10', brand: null },
        { name: 'Magnetyczny separator zanieczyszczeń', code: 'RASMDS-DS10', brand: null },
        { name: 'Zawór strefowy 3-drogowy z siłownikiem', code: 'RAS3W-ZV', brand: null },
      ],
    },
  },
  {
    id: 'pakiet-aquami-12',
    group: 'pakiety',
    groupLabel: 'Pakiety Premium',
    name: 'Pakiet Premium Aquami Split 12 kW',
    kicker: 'Pakiet Premium z akcesoriami',
    tagline: 'Kompletny zestaw pompy ciepła 12 kW z osprzętem hydraulicznym.',
    description: 'W pakiecie: zbiornik buforowy 100 l, wspornik montażowy Ivensis, zasobnik CWU 300 l, pompa obiegowa, separator zanieczyszczeń i zawór strefowy.',
    icon: 'bundle',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/52e47ee9-5cfc-411c-aa73-d3f06d4b8b65.png',
    gradient: ['#7a5a17', '#2a1e07'],
    glow: '#ffd479',
    badges: [{ icon: 'shield', text: '5 lat gwarancji na pompę ciepła' }],
    priceLabel: 'Pakiet 12 kW za',
    priceValue: '16000',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'bundle',
      variants: [{ label: 'Aquami Split 12 kW', oldPrice: '17 810,50 zł', newPrice: '16 000 zł', savings: '1 810,50 zł' }],
      mainItem: { name: 'Pompa ciepła Rotenso Aquami Split 12 kW', code: 'AQS120X3o + AQS160X13i', brand: 'rotenso' },
      accessories: [
        { name: 'Zbiornik buforowy Thermos Store 100 l', code: 'AQT100SBHA', brand: 'thermos' },
        { name: 'Wspornik montażowy do pomp ciepła Ivensis', code: 'IHG520S', brand: 'ivensis' },
        { name: 'Zbiornik CWU ze stali emaliowanej Thermos Ceramic 300 l', code: 'AQT300EC1A', brand: 'thermos' },
        { name: 'Pompa obiegowa', code: 'RASHSP-PH20', brand: null },
        { name: 'Magnetyczny separator zanieczyszczeń', code: 'RASMDS-DS20', brand: null },
        { name: 'Zawór strefowy 3-drogowy z siłownikiem', code: 'RAS3W-ZV21', brand: null },
      ],
    },
  },
  {
    id: 'pakiet-aquami-16',
    group: 'pakiety',
    groupLabel: 'Pakiety Premium',
    name: 'Pakiet Premium Aquami Split 16 kW',
    kicker: 'Pakiet Premium z akcesoriami',
    tagline: 'Kompletny zestaw pompy ciepła 16 kW z osprzętem hydraulicznym.',
    description: 'W pakiecie: zbiornik buforowy 100 l, wspornik montażowy Ivensis, zasobnik CWU 300 l, pompa obiegowa, separator zanieczyszczeń i zawór strefowy.',
    icon: 'bundle',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/d312c751-7ad2-438e-964d-6282fe931127.jpg',
    gradient: ['#7a5a17', '#2a1e07'],
    glow: '#ffd479',
    badges: [{ icon: 'shield', text: '5 lat gwarancji na pompę ciepła' }],
    priceLabel: 'Pakiet 16 kW za',
    priceValue: '17200',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'bundle',
      variants: [{ label: 'Aquami Split 16 kW', oldPrice: '18 210,50 zł', newPrice: '17 200 zł', savings: '1 010,50 zł' }],
      mainItem: { name: 'Pompa ciepła Rotenso Aquami Split 16 kW', code: 'AQS160X3o + AQS160X13i', brand: 'rotenso' },
      accessories: [
        { name: 'Zbiornik buforowy Thermos Store 100 l', code: 'AQT100SBHA', brand: 'thermos' },
        { name: 'Wspornik montażowy do pomp ciepła Ivensis', code: 'IHG520S', brand: 'ivensis' },
        { name: 'Zbiornik CWU ze stali emaliowanej Thermos Ceramic 300 l', code: 'AQT300EC1A', brand: 'thermos' },
        { name: 'Pompa obiegowa', code: 'RASHSP-PH20', brand: null },
        { name: 'Magnetyczny separator zanieczyszczeń', code: 'RASMDS-DS20', brand: null },
        { name: 'Zawór strefowy 3-drogowy z siłownikiem', code: 'RAS3W-ZV21', brand: null },
      ],
    },
  },
  {
    id: 'pakiet-airmi-8-10',
    group: 'pakiety',
    groupLabel: 'Pakiety Premium',
    name: 'Pakiet Premium Airmi Monoblock 8/10 kW',
    kicker: 'Pakiet Premium z akcesoriami',
    tagline: 'Kompletny zestaw monobloku Airmi z osprzętem hydraulicznym.',
    description: 'W pakiecie: zbiornik buforowy, wspornik montażowy Ivensis, zasobnik CWU, pompa obiegowa, separator zanieczyszczeń i zawór strefowy.',
    icon: 'bundle',
    gradient: ['#7a5a17', '#2a1e07'],
    glow: '#ffd479',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/4cf9915d-4048-46db-9677-12d3ec08438f.jpg',
    badges: [{ icon: 'shield', text: '5 lat gwarancji na pompę ciepła' }],
    priceLabel: 'Pakiet 8 kW już od',
    priceValue: '10500',
    priceSuffix: 'zł netto',
    brand: 'rotenso',
    validity: 'Oferta obowiązuje do 30.09.2026',
    detail: {
      type: 'bundle',
      variants: [
        { label: 'Airmi Monoblock 8 kW', oldPrice: '12 437,25 zł', newPrice: '10 500 zł', savings: '1 937,25 zł' },
        { label: 'Airmi Monoblock 10 kW', oldPrice: '12 757,25 zł', newPrice: '10 700 zł', savings: '2 057,25 zł' },
      ],
      mainItem: { name: 'Pompa ciepła Rotenso Airmi Monoblock 8 kW lub 10 kW', code: 'AIMW80X1 lub AIMW100X1', brand: 'rotenso' },
      accessories: [
        { name: 'Zbiornik buforowy Thermos Store 50 l', code: 'AQT50SBHA', brand: 'thermos' },
        { name: 'Wspornik montażowy do pomp ciepła Ivensis', code: 'IHG520M', brand: 'ivensis' },
        { name: 'Zbiornik CWU ze stali emaliowanej Thermos Ceramic 200 l', code: 'AQT200EC1A', brand: 'thermos' },
        { name: 'Pompa obiegowa', code: 'RASHSP-PH10', brand: null },
        { name: 'Magnetyczny separator zanieczyszczeń', code: 'RASMDS-DS10', brand: null },
        { name: 'Zawór strefowy 3-drogowy z siłownikiem', code: 'RAS3W-ZV', brand: null },
      ],
    },
  },

  // ---------------------------------------------------------------- AKCESORIA
  {
    id: 'akcesoria-rotenso',
    group: 'akcesoria',
    groupLabel: 'Akcesoria',
    name: 'Wyprzedaż akcesoriów Rotenso',
    kicker: 'Wyprzedaż',
    tagline: 'Sterowniki, moduły i filtry Rotenso w obniżonych cenach.',
    description: 'Ograniczona pula magazynowa — ceny instalatorskie netto znacząco obniżone.',
    icon: 'accessory',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/04119694-ffd4-483d-a989-97e700723ca9.jpg',
    gradient: ['#1b5fa0', '#08243d'],
    glow: '#7ec4ff',
    badges: [{ icon: 'tag', text: 'Wyprzedaż' }],
    priceLabel: 'Rabaty do',
    priceValue: '75%',
    priceSuffix: 'taniej',
    brand: 'rotenso',
    validity: '01.08.2026 – 31.08.2026 lub do wyczerpania stanów magazynowych',
    detail: {
      type: 'pricetable',
     columns: ['Kod produktu', 'Nazwa', 'Stara cena', 'Nowa cena netto'],
      rows: [
        ['MD-NIM05/E(ZG)', 'Styk Dry Contact RDCX', '330,00 zł', '101,75 zł'],
        ['MODUŁ ZATO IMOTO', 'Moduł sterownika Zato X - Imoto R14', '54,45 zł', '13,75 zł'],
        ['MODUŁ ZATO VERSU', 'Moduł sterownika Zato X - Versu R14', '54,45 zł', '41,25 zł'],
        ['MODUŁ ZATO UKURA', 'Moduł sterownika Zato X - Ukura R14', '54,45 zł', '26,40 zł'],
        ['SAVA CS HAHB', 'Sterownik Sava CS HAHB', '109,45 zł', '79,20 zł'],
        ['MODUŁ SAVA CS KPL', 'Moduł pracy grupowej Sava CS', '81,95 zł', '50,60 zł'],
        ['FILTR EPA FRESH', 'Filtr świeżego powietrza EPA Rotenso Fresh R15', '37,95 zł', '23,10 zł'],
        ['MFBR IMOTO', 'Moduł multifunkcyjny MFBR IMOTO', '156,75 zł', '33,00 zł'],
        ['N26XI R14', 'Klimatyzator kanałowy Rotenso Nevo N26Xi R14 (jednostka wewnętrzna)', '906,95 zł', '200,75 zł'],
        ['T35VI R11', 'Klimatyzator kasetonowy Rotenso T35Vi R11 (jednostka wewnętrzna)', '650,00 zł', '200,75 zł'],
        ['CCM-18A/N', 'Bramka BMS MODBUS 64', '8 525,00 zł', '7 700,00 zł'],
      ],
      footnote: TERMS.standard,
    },
  },
];

/* ============================================================================
   MARKA: LG — czyszczenie magazynu
   ============================================================================ */

function tagLgType(name) {
  const n = name.toUpperCase();
  if (n.includes('POMPA CIEP')) return 'pompy';
  if (n.includes('KLIMATYZATOR')) return 'klimatyzacje';
  return 'akcesoria';
}

const LG_ROWS_RAW = [
  ['AA09SP.U18', 'KLIMATYZATOR LG AA09SP.U18 ZEW.', '1 250 zł'],
  ['AA12SP.U18', 'KLIMATYZATOR LG AA12SP.U18 ZEW.', '1 250 zł'],
  ['AB09BK.UA3', 'KLIMATYZATOR LG ARTCOOL AB09BK.UA3 ZEW', '1 200 zł'],
  ['AC09BK.UA3', 'KLIMATYZATOR LG ARTCOOL AC09BK.UA3 ZEW', '1 250 zł'],
  ['AC12BK.UA3', 'KLIMATYZATOR LG ARTCOOL AC12BK.UA3 ZEW', '1 400 zł'],
  ['AHCS100H0', 'LG CZUJNIK CO2 NAŚCIENNY AHCS100H0', '350 zł'],
  ['DM07RK.NSJ', 'KLIMATYZATOR LG DELUXE MULTI DM07RK.NSJ WEW.JEDN', '500 zł'],
  ['FM41AH.U34', 'KLIMATYZATOR LG MULTI FDX FM41AH.U34 ZEW.JEDNOSTKA', '5 500 zł'],
  ['H09S1D.U12', 'KLIMATYZATOR LG SOFT AIR DELUXE H09S1D.U12 ZEW.', '990 zł'],
  ['HU143MA.U33', 'POMPA CIEPŁA LG THERMA V HU143MA.U33 ZEW SPLIT', '6 600 zł'],
  ['HU163MA.U33', 'POMPA CIEPŁA LG THERMA V HU163MA.U33 ZEW SPLIT', '7 000 zł'],
  ['MS07ET.NSA', 'KLIMATYZATOR LG STANDARD 2 MS07ET.NSA WEW', '450 zł'],
  ['MU2R15.U13', 'KLIMATYZATOR LG MU2R15.U13 ZEW.', '3 100 zł'],
  ['PLNWKB000', 'LG MULTI V PLNWKB000', '2 500 zł'],
  ['PM05SK.NSA', 'KLIMATYZATOR LG STANDARD PM05SK.NSA WEW. ŚCIENNA', '550 zł'],
  ['PMBD3620', 'LG DYSTRYBUTOR MULTI FDX PMBD3620', '650 zł'],
  ['PMBD3640', 'LG DYSTRYBUTOR MULTI FDX PMBD3640', '1 150 zł'],
  ['PMBL5620', 'LG ROZGAŁĘŹNIK MULTI FDX PMBL5620', '300 zł'],
  ['PMUB111A', 'LG ROZGAŁĘŹNIK SYNCHRO PMUB111A', '300 zł'],
  ['PQCSZ250S0', 'LG PROSTY STEROWNIK CENTRALNY PQCSZ250S0', '1 500 zł'],
  ['PQRCVCL0QW', 'LG STEROWNIK PRZEWODOWY PQRCVCL0QW', '150 zł'],
  ['PREMTB101', 'LG PREMTB101.ENCXCOM STEROWNIK PRZEWODOWY', '450 zł'],
  ['PTDCQ', 'LG OBUDOWA KASET PTDCQ', '400 zł'],
  ['PTEGM0', 'LG OPUSZCZANY FILTR KASET PTEGM0', '800 zł'],
  ['PTVSAA0', 'LG CZUJNIK OBECNOŚCI CZŁOWIEKA PTVSAA0', '180 zł'],
  ['S09ET.UA3', 'KLIMATYZATOR LG STANDARD 2 S09ET.UA3 ZEW', '750 zł'],
  ['S09ET.UA3S', 'KLIMATYZATOR LG STANDARD 2 S09ET.UA3S ZEW', '750 zł'],
  ['UM24FH.N20', 'KLIMATYZATOR LG KANAŁOWY UM24FH.N20 WEW', '1 450 zł'],
  ['UM42F.N20', 'KLIMATYZATOR LG KANAŁOWY UM42F.N20 WEW', '1 800 zł'],
  ['UT09FH.NQ0', 'KLIMATYZATOR LG KASETONOWY UT09FH.NQ0 WEW', '1 100 zł'],
  ['UT24FH.NA0', 'KLIMATYZATOR LG KASETONOWY UT24FH.NA0 WEW', '1 750 zł'],
  ['UT36F.NY0', 'KLIMATYZATOR LG KASETONOWY UT36F.NY0 WEW', '2 350 zł'],
  ['UT42FH.NA0', 'KLIMATYZATOR LG KASETONOWY UT42FH.NA0 WEW', '3 000 zł'],
  ['UT48F.NA0', 'KLIMATYZATOR LG KASETONOWY UT48F.NA0 WEW', '3 000 zł'],
  ['UU70W.U34', 'KLIMATYZATOR LG UU70W.U34 ZEWNĘTRZNA JEDNOSTKA', '7 500 zł'],
  ['P09SND.NS0', 'KLIMATYZATOR LG P09SND.NS0 WEW.', '930 zł'],
  ['EZ12CYU.CA31', 'KLIMATYZATOR LG EZ12CYU.CA31 ZEW.', '1 200 zł'],
  ['AA18SP.U18', 'KLIMATYZATOR LG AA18SP.U18 ZEW.', '1 900 zł'],
  ['P12SND.U12A', 'KLIMATYZATOR LG P12SND.U12A ZEW.', '1 450 zł'],
  ['PREMTA211.ENCXCOM', 'LG PREMTA211 STEROWNIK PRZEWODOWY', '1 080 zł'],
  ['EZ09CYN.CSJ1', 'KLIMATYZATOR LG EZ09CYN.CSJ1 (JEDNOSTKA WEWN.)', '500 zł'],
  ['EZ12CYN.CSJ1', 'KLIMATYZATOR LG EZ12CYN.CSJ1 (JEDNOSTKA WEWN.)', '500 zł'],
];

const LG_ROWS = LG_ROWS_RAW.map((r) => ({ code: r[0], name: r[1], price: r[2], type: tagLgType(r[1]) }));

const LG_CATEGORIES = [
  {
    id: 'lg-clearance',
    group: 'wyprzedaz',
    groupLabel: 'Wyprzedaż magazynu',
    name: 'Czyszczenie magazynu LG',
    kicker: 'Sprawdź ekstra ceny!',
    tagline: 'Klimatyzacje • Pompy ciepła • Akcesoria — oferta ograniczona do wyczerpania zapasów.',
    description:
      `Ponad ${LG_ROWS.length} pozycji magazynowych LG w bardzo atrakcyjnych, jednorazowych cenach. Wysyłka gratis na cały asortyment objęty wyprzedażą.`,
    icon: 'warehouse',
    image: 'https://thermosilesia.pl/media/cache/view_landing_page_promotions_tile/assets/upload/cms/landing_page/f857e489-061e-468e-b5da-954bfa64ee53.jpg',
    gradient: ['#a10d24', '#38040c'],
    glow: '#ff5c72',
    badges: [
      { icon: 'truck', text: 'Wysyłka gratis' },
      { icon: 'tag', text: 'Oferta ograniczona' },
    ],
    priceLabel: 'Pozycji w wyprzedaży',
    priceValue: String(LG_ROWS.length),
    priceSuffix: 'produktów',
    brand: 'lg',
    validity: '01.08.2026 – 31.08.2026 lub do wyczerpania stanów magazynowych',
    detail: {
      type: 'pricetable-filtered',
      columns: ['Kod produktu', 'Nazwa', 'Cena promocyjna netto'],
      filters: [
        { id: 'wszystko', label: 'Wszystko' },
        { id: 'klimatyzacje', label: 'Klimatyzatory' },
        { id: 'pompy', label: 'Pompy ciepła' },
        { id: 'akcesoria', label: 'Akcesoria i sterowniki' },
      ],
      rows: LG_ROWS,
      footnote: TERMS.standard,
    },
  },
];

/* ============================================================================
   REJESTR MAREK
   ============================================================================ */

const BRANDS = {
  rotenso: {
    id: 'rotenso',
    name: 'Rotenso',
    tagline: 'Live better',
    logo: 'rotenso',
    pillLogo: 'rotensoR',
    theme: { accent: '#c8102e', accentSoft: '#e2542d' },
    categories: ROTENSO_CATEGORIES,
  },
  lg: {
    id: 'lg',
    name: 'LG',
    tagline: 'Life is Good',
    logo: 'lg',
    // LG nie jest "naszą" marką jak Rotenso — w nagłówku po lewej pokazujemy
    // logo dystrybutora (Thermosilesia), a nie logo LG.
    headerLogo: 'thermosilesia',
    theme: { accent: '#c8102e', accentSoft: '#8a0a1c' },
    categories: LG_CATEGORIES,
  },
};

const BRAND_ORDER = ['rotenso', 'lg'];
